weights: ../yolov5/yolov5s.pt
cfg: ../yolov5/models/yolov5s.yaml
data: data.yaml
hyp: ../yolov5/data/hyps/hyp.scratch.yaml
epochs: 200
batch_size: 8
imgsz: 1024
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: cpu
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: ../yolov5/runs/train
name: wheat_detection
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: ../yolov5/runs/train/wheat_detection9
